### ISSUE TITLE
CSS maakt me droevig

### ISSUE THREAD

**Issue by ghost** [IvarSchuyt/profile-card-Ivar-Schuyt#4]
Hoi, ik heb even in je CSS gekeken en moest daar snel mee stoppen. Ik werd er namelijk een beetje droevig van.

Waarom?

- Geen spatie's tussen selector en openings haakje
- Geen spatie's tussen properties en value's
- Geen enter's na sluittag.

**Comment by IvarSchuyt** [comment]
ja maar minder characters

**Comment by ghost** [comment]
@IvarSchuyt ok dat is een goede reden. Het spijt me, ik ben wel nog een beetje droevig
